version: '3.5'
services:
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud:latest
    env_file:
      - ./config.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7080:443"
    volumes:
      - ${DIR_MOUNT}/config:/config
      - ${DIR_MOUNT}/data:/data
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver
