version: '3.5'
services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    env_file:
      - ./config.env
    ports:
      - "7080:80"
    volumes:
      - ${DIR_MOUNT}/www:/var/www/html
    restart: unless-stopped
  mariadb:
    container_name: nextcloud-db
    image: mariadb
    env_file:
      - ./config.env
    volumes:
      - ${DIR_MOUNT}/mysql:/var/lib/mysql
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver