version: '3.5'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    env_file:
      - ./config.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7878:7878"
    volumes:
      - ${DIR_MOUNT}/config:/config
      - ${DIR_MOUNT}/movies:/movies
      - ${DIR_TRANSMISSION}:/data
      - ${DIR_MEDIA}:/downloads
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver