version: '3.5'
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    env_file:
      - ./config.env
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9117:9117"
    volumes:
      - ${DIR_MOUNT}/config:/config
      - ${DIR_MOUNT}/downloads:/downloads
    restart: always
networks:
  default:
    external:
      name: homeserver