version: '3.5'
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    env_file:
      - ./config.env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DIR_MOUNT}/config:/config
      - ${DIR_MOUNT}/downloads:/downloads
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver