version: '3.5'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    volumes:
      - ${DIR_MOUNT}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver