version: '3.5'
services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    privileged: true
    env_file:
      - ./config.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "9091:9091"
    volumes:
      - ${DIR_MOUNT}:/data
      - ${DIR_MOUNT}/config:/config
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver
